change-id = 136941

[llvm]
# They deleted llvm wtf
download-ci-llvm = false
optimize = true
thin-lto = true
link-shared = false
ninja = true
targets = "X86"
link-jobs = 0
cflags = "-Qunused-arguments -O2 -msse2 /clang:-O3"
cxxflags = "-Qunused-arguments -O2 -msse2 /clang:-O3"
ldflags = "-Wl,-O3 -msse2"
polly = true
clang = true
clang-cl = "C:/DEV/LLVM/bin/clang-cl.exe"
version-suffix = "-eRust9x-dev"

[build]
build-stage = 2
cargo-native-static = false
# When compiling from source, you usually want all tools.
docs = false
extended = true
tools = [
    "cargo"
]
build = "x86_64-pc-windows-msvc"
target = [
    "i586-rust9x-windows-msvc",
    "i686-rust9x-windows-msvc",
    "x86_64-rust9x-windows-msvc",
    "x86_64-pc-windows-msvc",
]
optimized-compiler-builtins = true
#verbose = 1
jobs = 0

[rust]
channel = "dev"
codegen-backends = ["llvm"]
codegen-units = 1
codegen-units-std = 1
debug = false
dist-src = false
download-rustc = false
#jemalloc = true
lld = true
#lto = "thin"
optimize = 3
strip = true
optimize-tests = true
thin-lto-import-instr-limit = 100
validate-mir-opts = 3
use-lld = "self-contained"
description = "eRust9x"
debuginfo-level = 0
debug-assertions = false

# for creating a downloadable package: python x.py dist.
[dist]
src-tarball = false
compression-profile = "best"
compression-formats = ["xz"]

[install]
prefix = "../dist/rust"
sysconfdir = "."
